In [30]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import svm

In [31]:
dataset = pd.read_csv("train.csv")
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [32]:
dataset["Embarked"] = np.where(dataset["Embarked"].isnull(),dataset["Embarked"].mode(),dataset["Embarked"])
dataset["Age"] = np.where(dataset["Age"].isnull(),dataset["Age"].mean(),dataset["Age"])
le = preprocessing.LabelEncoder()
le.fit(dataset["Sex"])
dataset["Sex"] = le.transform(dataset["Sex"])
le.fit(dataset["Sex"])
le.fit(dataset["Embarked"])
dataset["Embarked"] = le.transform(dataset["Embarked"])

In [33]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [34]:
dataset1= dataset.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)
dataset1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [40]:
def get_svn_score(dv):
    y=dataset1[dv]
    X= dataset1.drop([dv],axis=1)
    X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=0)
    clf = svm.SVC(gamma=0.01,C=100)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    a_score = accuracy_score(y_test,y_pred,normalize=True)
    c_matrix = confusion_matrix(y_test,y_pred)
    print("SVN accouracy score for {} is {}".format(dv,a_score))
    print("Confusion matrix for {} is ".format(dv))
    print(c_matrix)
    print("="*100)
        

get_svn_score("Pclass")

SVN accouracy score for Pclass is 0.8955223880597015
Confusion matrix for Pclass is 
[[ 58   2   0]
 [  6  40   6]
 [  3  11 142]]


In [41]:
dataset1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [43]:
dvs = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']
for d in dvs:
    get_svn_score(d)

SVN accouracy score for Survived is 0.7611940298507462
Confusion matrix for Survived is 
[[141  27]
 [ 37  63]]
SVN accouracy score for Pclass is 0.8955223880597015
Confusion matrix for Pclass is 
[[ 58   2   0]
 [  6  40   6]
 [  3  11 142]]
SVN accouracy score for Sex is 0.75
Confusion matrix for Sex is 
[[ 58  41]
 [ 26 143]]
SVN accouracy score for SibSp is 0.7425373134328358
Confusion matrix for SibSp is 
[[161  18   2   0   0   0]
 [ 33  29   3   0   0   0]
 [  1   3   1   2   0   0]
 [  1   2   0   3   0   0]
 [  2   2   0   0   3   0]
 [  0   0   0   0   0   2]]
SVN accouracy score for Parch is 0.8283582089552238
Confusion matrix for Parch is 
[[193   5   6   0   0   0]
 [ 21  17   1   1   0   0]
 [  6   3  12   0   0   0]
 [  0   0   0   0   0   0]
 [  0   1   1   0   0   0]
 [  0   1   0   0   0   0]]
SVN accouracy score for Embarked is 0.746268656716418
Confusion matrix for Embarked is 
[[ 24   4  32]
 [  1  10  10]
 [ 16   5 166]]
