In [25]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [26]:
data = pd.read_csv("train.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
data = data.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)

In [28]:
data["Age"] = np.where(data["Age"].isnull(),data["Age"].mean(),data["Age"])
#data["Cabin"] = np.where(data["Cabin"].isnull(),data["Age"].mode(),data["Cabin"])
data["Embarked"] = np.where(data["Embarked"].isnull(),data["Embarked"].mode(),data["Embarked"])
data["Age"].isnull().sum()

0

In [29]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [30]:
le = preprocessing.LabelEncoder()

In [31]:
le.fit(data["Sex"])
data["Sex"] = le.transform(data["Sex"])

In [32]:
#print(le.classes_)

In [33]:
le.fit(data["Embarked"])
data["Embarked"] = le.transform(data["Embarked"])
print(data["Sex"])
print("===========================")
print(data["Embarked"])

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int32
0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Name: Embarked, Length: 891, dtype: int32


In [34]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [35]:
data.columns


Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [36]:
from sklearn.naive_bayes import *
def naive_bayes(x,y):
    X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3,random_state=0)
    clf = BernoulliNB()
    y_pred=clf.fit(X_train,Y_train).predict(X_test)
    print(accuracy_score(Y_test,y_pred,normalize=True))
    print("========================================")
    print(confusion_matrix(Y_test,y_pred))
    

In [42]:
dv = ['Survived', 'Pclass', 'Sex',  'SibSp', 'Parch', 'Embarked']
#dv = ['Survived']
for d in dv:
    y = data[d]
    x = data.drop(d,axis=1)
    print("Accuracy Score and Confusion matrix for {} is".format(d))
    naive_bayes(x,y)   

Accuracy Score and Confusion matrix for Survived is
0.7835820895522388
[[137  31]
 [ 27  73]]
Accuracy Score and Confusion matrix for Pclass is
0.5932835820895522
[[ 33   0  27]
 [ 21   0  31]
 [ 29   1 126]]
Accuracy Score and Confusion matrix for Sex is
0.7835820895522388
[[ 72  27]
 [ 31 138]]
Accuracy Score and Confusion matrix for SibSp is
0.6791044776119403
[[162  19   0   0   0   0]
 [ 45  20   0   0   0   0]
 [  4   3   0   0   0   0]
 [  4   2   0   0   0   0]
 [  4   3   0   0   0   0]
 [  1   1   0   0   0   0]]
Accuracy Score and Confusion matrix for Parch is
0.7425373134328358
[[189  15   0   0   0]
 [ 30  10   0   0   0]
 [ 17   4   0   0   0]
 [  2   0   0   0   0]
 [  1   0   0   0   0]]
Accuracy Score and Confusion matrix for Embarked is
0.6977611940298507
[[  0   0  60]
 [  0   0  21]
 [  0   0 187]]
