# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
randnums= np.random.randint(1,100, size=(3,3,3))
randnums

array([[[49, 95, 87],
        [38, 91, 61],
        [40, 56, 60]],

       [[85, 12, 44],
        [64, 63,  7],
        [21, 51, 86]],

       [[39, 10, 15],
        [66, 39, 21],
        [94, 71, 14]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
a= np.zeros((5,5),dtype=int)
np.shape(a)[0]
for i in range(1,np.shape(a)[0]):
    a[i][i-1]=i
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [93]:
a=np.zeros((8,8),dtype=int)
a
a[1::2,0::2]=1
a[0::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [48]:
from sklearn.preprocessing import normalize
randnums= np.random.randint(1,100, size=(5,5))
print("Array before normalization")
print(randnums)
print("="*100)
randnums1 = normalize(randnums)
print("Array after normalization")
print(randnums1)
print("="*100)


Array before normalization
[[72 42 57 21  7]
 [26 27 48 74 81]
 [15 89 23 77 95]
 [87 37 85 95 23]
 [39 41 84  8 55]]
Array after normalization
[[0.69647349 0.4062762  0.55137485 0.2031381  0.0677127 ]
 [0.20719927 0.21516847 0.38252173 0.589721   0.64550542]
 [0.09758175 0.57898503 0.14962535 0.50091963 0.61801773]
 [0.54251169 0.23072336 0.53004016 0.59239782 0.14342263]
 [0.33757694 0.35488858 0.7270888  0.06924655 0.47607005]]


# 5.  How to find common values between two arrays?

In [50]:
#Using intersect1d function
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
np.intersect1d(array1, array2)


array([10, 40])

# 6.How to get the dates of yesterday, today and tomorrow?

In [59]:
a = np.datetime64('today')
print("Today:",a)
b = np.datetime64('today')- np.timedelta64(1)
print("Yesterday:",b)
c = np.datetime64('today')+ np.timedelta64(1)
print("Yesterday:",c)

Today: 2020-07-27
Yesterday: 2020-07-26
Yesterday: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [63]:
a= np.random.randint(1,100, size=(5))
b= np.random.randint(1,100, size=(5))
print(a)
print(b)
print(np.equal(a,b)) # this is to check each element of array
c = a==b
print(c.all()) # to check if array is indentical

[87 36 21 11 48]
[81 42 54 35 93]
[False False False False False]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [96]:
a= np.random.randint(1,100, size=(10))
print("Array is",a)
print("Maximum element in array is",max(a))
index = np.argmax(a)
print("Index of maximum element is",index)
a[index]=0
print("Array after replacing macx value with 0 is",a)

Array is [33  5 54 75 19 82 13  6 21 80]
Maximum element in array is 82
Index of maximum element is 5
Array after replacing macx value with 0 is [33  5 54 75 19  0 13  6 21 80]


# 9. How to print all the values of an array?

In [64]:
#Using  print() 
a= np.random.randint(1,100, size=(5))
b= np.random.randint(1,100, size=(5))
print(a)
print(b)

[26 39 88 68  5]
[13 42 98 50  1]


# 10.Subtract the mean of each row of a matrix

In [86]:
a = np.random.randint(1,100, size=(5,5))
print(a)
c= a-a.mean(axis=1,keepdims=True)
print(c)


[[58 45 78 17  9]
 [71 98 26 11 24]
 [28 57 34 86 15]
 [ 3 71 72 92 62]
 [64 18  3 45 95]]
[[ 16.6   3.6  36.6 -24.4 -32.4]
 [ 25.   52.  -20.  -35.  -22. ]
 [-16.   13.  -10.   42.  -29. ]
 [-57.   11.   12.   32.    2. ]
 [ 19.  -27.  -42.    0.   50. ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [25]:
a= np.random.randint(1,100, size=(100))
print("Array is ",a)
b= np.random.randint(1,10, size=(10))
print("Indexs are ",b)
c = a[b]
print("Fetched array before adding 1",c)
c=c+1
print("New array",c)

Array is  [10 25 26 49 99 28 24 70 72 32 62 49 71 15 70 12 11 51 33 21 45 19 75 82
 28 21  7 56 56 98  5 10 98 69 73 31 75  1 61 49 49 23 77 98 22 44 10 93
 51 91 65 28 60  9 63 87 56 91 10 95 70 82 17 73 46 56 56 35 82 14 48 57
 88 19 49 12 21 82 89 30 46 50 49 74  1 57 65 46 21 86 55 16 92 42 62 82
 36 21 26 50]
Indexs are  [3 8 3 2 4 6 2 1 5 9]
Fetched array before adding 1 [49 72 49 26 99 24 26 25 28 32]
New array [ 50  73  50  27 100  25  27  26  29  33]


# 12.How to get the diagonal of a dot product?

In [115]:
a = np.random.randint(1,100, size=(3,3))
b = np.random.randint(1,100, size=(3,3))
print(a)
print(b)
c = np.dot(a,b)
print("Dot produt is")
print(c)
d = np.diag(c)
print("Dignola is",d)

[[38 13 47]
 [94 66 97]
 [42 19 26]]
[[45 87 39]
 [72 52 12]
 [ 4 48 23]]
Dot produt is
[[ 2834  6238  2719]
 [ 9370 16266  6689]
 [ 3362  5890  2464]]
Dignola is [ 2834 16266  2464]


# 13.How to find the most frequent value in an array?

In [99]:
a = np.random.randint(1,100, size=(25))
print("Array is",a)
print(np.bincount(a).argmax())

Array is [86  5 48 29 92 67 87 65 75 42 28 94 96 54 67 70 99 48 36 24 58 68 34 50
  4]
48


# 14.How to get the n largest values of an array

In [111]:
a = np.random.randint(1,100, size=(25))
print(a)
b = -np.sort(-a)
n = input("Enter value of n")
count = 0
while count<int(n):
    print(b[count])
    count+=1


[95 52 10 86 81 93 77 46 99 82 82 46 38 52 37 43 13 58 21 98 61 56  2 56
 23]
Enter value of n3
99
98
95


# 15.How to create a record array from a regular array?

In [117]:
a = np.random.randint(1,100, size=(5))
b = np.random.randint(1,100, size=(5))
c = np.core.records.fromarrays([a,b])
print(c)

[(20, 48) ( 6, 56) (36,  2) (45, 72) ( 2, 72)]
